[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "BSD-2-Clause",
    "CC0-1.0",
]
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]

[bans]
multiple-versions = "warn"
allow-wildcard-paths = true
wildcards = "warn"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/AxiomaticSemantics/bevy", "https://github.com/AxiomaticSemantics/bevy_tweening"]

